package main

var playerList []Player = []Player{
	AssassinationClassroom(true),
	Burglar(true),
	Careful(true),
	Careless(true),
	CCCP(true),
	Centrist(true),
	CheckCapture(true),
	Coward(true),
	Edgelord(true),
	EdgierEdgelord(true),
	FirstValid(true),
	Huddle(true),
	Human(true),
	KingOfTheHill(true),
	KnightlyOrder(true),
	LastValid(true),
	MaxOpponentMoves(true),
	MinOpponentMoves(true),
	Pacifist(true),
	PawnsFirst(true),
	QueenOfTheHill(true),
	RandomMove(true),
	Schizophrenia(true),
	newSinglePiece(),
	Slow(true),
	newUCI("stockfish"),
	SuicideKing(true),
	Swarm(true),
	Traveller(true),
}
